// <auto-generated />
namespace BlockBuster.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Locacao_Copia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Locacao_Copia));
        
        string IMigrationMetadata.Id
        {
            get { return "201311092048252_Locacao_Copia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
