// <auto-generated />
namespace BlockBuster.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Genero_Titulo_TipoTitulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Genero_Titulo_TipoTitulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201311092017331_Genero_Titulo_TipoTitulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
